version: 1.0.0-ci-{build}
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2017
configuration: Debug
before_build:
  - nuget restore SocksSharp.sln
build:
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: normal
after_build:
  - ps: "Get-ChildItem *.nupkg -Recurse | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }"
test: off
deploy:
  - provider: NuGet
    server: https://www.myget.org/F/sockssharp/api/v2/package
    api_key:
      secure: K+dcFuAQ7VnPljVdPE1t1IBtoaQh7QW4fCYhqLQH35UIrIEqXrbXFk9qOx8nzkIb
    symbol_server: https://www.myget.org/F/sockssharp/api/v2/package
    on:
      branch: dev