version: 1.1.0-ci-{build}
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2017
configuration: Debug
before_build:
  - nuget restore SocksSharp.sln
build:
  publish_nuget: false
  publish_nuget_symbols: false
  verbosity: normal
  
test: off
deploy:
  - provider: NuGet
    api_key:
      secure: XDyu2Wr5aDX3OW1GTJTSIq2y5wq5q8OFX9gJEHiRdwHGmCKNki/fI0vREBq1zYWR
    artifact: /.*\.nupkg/
    on:
      branch: dev
