version: 1.0.0-beta-{build}
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2017
configuration: Debug
before_build:
  - nuget restore SocksSharp.sln
build:
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: normal
after_build:
  - ps: "Get-ChildItem *.nupkg -Recurse | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }"
test: off
deploy:
  - provider: NuGet
    api_key:
      secure: XDyu2Wr5aDX3OW1GTJTSIq2y5wq5q8OFX9gJEHiRdwHGmCKNki/fI0vREBq1zYWR
    on:
      branch: dev